// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 44.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'stayhome';

  static const String assets_FindLocation_svg = 'assets/FindLocation.svg';
  static const String stayhome$assets_FindLocation_svg = 'packages/stayhome/assets/FindLocation.svg';

  static const String assets_Gloves_svg = 'assets/Gloves.svg';
  static const String stayhome$assets_Gloves_svg = 'packages/stayhome/assets/Gloves.svg';

  static const String assets_Lemon_svg = 'assets/Lemon.svg';
  static const String stayhome$assets_Lemon_svg = 'packages/stayhome/assets/Lemon.svg';

  static const String assets_Let_s_Chill_svg = 'assets/Let’s Chill.svg';
  static const String stayhome$assets_Let_s_Chill_svg = 'packages/stayhome/assets/Let’s Chill.svg';

  static const String assets_Mask_svg = 'assets/Mask.svg';
  static const String stayhome$assets_Mask_svg = 'packages/stayhome/assets/Mask.svg';

  static const String assets_Paper_svg = 'assets/Paper.svg';
  static const String stayhome$assets_Paper_svg = 'packages/stayhome/assets/Paper.svg';

  static const String assets_antidot_svg = 'assets/antidot.svg';
  static const String stayhome$assets_antidot_svg = 'packages/stayhome/assets/antidot.svg';

  static const String assets_attention_svg = 'assets/attention.svg';
  static const String stayhome$assets_attention_svg = 'packages/stayhome/assets/attention.svg';

  static const String assets_bell_svg = 'assets/bell.svg';
  static const String stayhome$assets_bell_svg = 'packages/stayhome/assets/bell.svg';

  static const String assets_box_svg = 'assets/box.svg';
  static const String stayhome$assets_box_svg = 'packages/stayhome/assets/box.svg';

  static const String assets_covid_image_png = 'assets/covid_image.png';
  static const String stayhome$assets_covid_image_png = 'packages/stayhome/assets/covid_image.png';

  static const String assets_delivery_star_png = 'assets/delivery_star.png';
  static const String stayhome$assets_delivery_star_png = 'packages/stayhome/assets/delivery_star.png';

  static const String assets_dots_png = 'assets/dots.png';
  static const String stayhome$assets_dots_png = 'packages/stayhome/assets/dots.png';

  static const String assets_dots_registration_png = 'assets/dots_registration.png';
  static const String stayhome$assets_dots_registration_png = 'packages/stayhome/assets/dots_registration.png';

  static const String assets_dots_violet_png = 'assets/dots_violet.png';
  static const String stayhome$assets_dots_violet_png = 'packages/stayhome/assets/dots_violet.png';

  static const String assets_earth_active_svg = 'assets/earth_active.svg';
  static const String stayhome$assets_earth_active_svg = 'packages/stayhome/assets/earth_active.svg';

  static const String assets_faq_svg = 'assets/faq.svg';
  static const String stayhome$assets_faq_svg = 'packages/stayhome/assets/faq.svg';

  static const String assets_filled_star_svg = 'assets/filled_star.svg';
  static const String stayhome$assets_filled_star_svg = 'packages/stayhome/assets/filled_star.svg';

  static const String assets_flask_svg = 'assets/flask.svg';
  static const String stayhome$assets_flask_svg = 'packages/stayhome/assets/flask.svg';

  static const String assets_friends_inactve_svg = 'assets/friends_inactve.svg';
  static const String stayhome$assets_friends_inactve_svg = 'packages/stayhome/assets/friends_inactve.svg';

  static const String assets_garlic_svg = 'assets/garlic.svg';
  static const String stayhome$assets_garlic_svg = 'packages/stayhome/assets/garlic.svg';

  static const String assets_health_png = 'assets/health.png';
  static const String stayhome$assets_health_png = 'packages/stayhome/assets/health.png';

  static const String assets_hide_password_svg = 'assets/hide_password.svg';
  static const String stayhome$assets_hide_password_svg = 'packages/stayhome/assets/hide_password.svg';

  static const String assets_info_svg = 'assets/info.svg';
  static const String stayhome$assets_info_svg = 'packages/stayhome/assets/info.svg';

  static const String assets_invisability_svg = 'assets/invisability.svg';
  static const String stayhome$assets_invisability_svg = 'packages/stayhome/assets/invisability.svg';

  static const String assets_logout_svg = 'assets/logout.svg';
  static const String stayhome$assets_logout_svg = 'packages/stayhome/assets/logout.svg';

  static const String assets_map_svg = 'assets/map.svg';
  static const String stayhome$assets_map_svg = 'packages/stayhome/assets/map.svg';

  static const String assets_me_svg = 'assets/me.svg';
  static const String stayhome$assets_me_svg = 'packages/stayhome/assets/me.svg';

  static const String assets_pangolina_png = 'assets/pangolina.png';
  static const String stayhome$assets_pangolina_png = 'packages/stayhome/assets/pangolina.png';

  static const String assets_rating_svg = 'assets/rating.svg';
  static const String stayhome$assets_rating_svg = 'packages/stayhome/assets/rating.svg';

  static const String assets_sanitaiser_svg = 'assets/sanitaiser.svg';
  static const String stayhome$assets_sanitaiser_svg = 'packages/stayhome/assets/sanitaiser.svg';

  static const String assets_search_svg = 'assets/search.svg';
  static const String stayhome$assets_search_svg = 'packages/stayhome/assets/search.svg';

  static const String assets_settings_svg = 'assets/settings.svg';
  static const String stayhome$assets_settings_svg = 'packages/stayhome/assets/settings.svg';

  static const String assets_show_more_svg = 'assets/show_more.svg';
  static const String stayhome$assets_show_more_svg = 'packages/stayhome/assets/show_more.svg';

  static const String assets_show_password_svg = 'assets/show_password.svg';
  static const String stayhome$assets_show_password_svg = 'packages/stayhome/assets/show_password.svg';

  static const String assets_sloth_png = 'assets/sloth.png';
  static const String stayhome$assets_sloth_png = 'packages/stayhome/assets/sloth.png';

  static const String assets_stay_home_png = 'assets/stay_home.png';
  static const String stayhome$assets_stay_home_png = 'packages/stayhome/assets/stay_home.png';

  static const String assets_stay_home_drawer_png = 'assets/stay_home_drawer.png';
  static const String stayhome$assets_stay_home_drawer_png = 'packages/stayhome/assets/stay_home_drawer.png';

  static const String assets_stay_home_min_png = 'assets/stay_home_min.png';
  static const String stayhome$assets_stay_home_min_png = 'packages/stayhome/assets/stay_home_min.png';

  static const String assets_storoz_png = 'assets/storoz.png';
  static const String stayhome$assets_storoz_png = 'packages/stayhome/assets/storoz.png';

  static const String assets_tekila_png = 'assets/tekila.png';
  static const String stayhome$assets_tekila_png = 'packages/stayhome/assets/tekila.png';

  static const String assets_you_image_svg = 'assets/you_image.svg';
  static const String stayhome$assets_you_image_svg = 'packages/stayhome/assets/you_image.svg';

  static const String assets_zalozhnik_png = 'assets/zalozhnik.png';
  static const String stayhome$assets_zalozhnik_png = 'packages/stayhome/assets/zalozhnik.png';

  static const String assets_zarazita_png = 'assets/zarazita.png';
  static const String stayhome$assets_zarazita_png = 'packages/stayhome/assets/zarazita.png';
}
